#include "globals.h"

struct ADMISSIONS_DATA *ADMISSIONS_TABLE;
struct PATIENTS_DATA *PATIENTS_TABLE;
struct EVENTS_DATA_TABLE *FEATURES_TABLE;
struct DRUG_DATA_TABLE *PRESCRIPTION_TABLE;
struct ICUSTAY_DATA *ICUSTAY_TABLE;
struct TRANSFER_DATA *TRANSFERS_TABLE;
struct NOTE_DATA *NOTEEVENT_TABLE;